### ISSUE TITLE
Unknown editor freeze in play mode.

### ISSUE THREAD

**Issue by 2Hadolphin** [handzlikchris/Unity.MissingUnityEvents#15]
After finish load scene for 5~10 seconds,
UnityEditor will freeze and not respond.

Unity 2022.1.10f1

[Editor.log](https://github.com/handzlikchris/Unity.MissingUnityEvents/files/9503821/Editor.log)

**Comment by handzlikchris** [comment]
@2Hadolphin looks like this is already integrated in your project. It's hard to say why would that happen as it's likely a mix caused by combination of things in your project that happens.

Probably best to try to and replicate on smalles possible project to narrow the issue down, with that if you share the project files where issue can be recreated I may be able to help.

But once you've narrowed it down you'll probably already know what's causing it.

**Comment by 2Hadolphin** [comment]
Thanks for your reply,
I found what's going wrong,
If there is a script invoke job system in the scene,
it will cause editor freeze without any error log.
Would this happen when using plugin from AssetStore version?

`Unity.Jobs.IJobExtensions.Schedule<T>()(this T jobData, JobHandle dependsOn = default(JobHandle))

public unsafe static JobHandle Schedule<T>(this T jobData, JobHandle dependsOn = default(JobHandle))`

Really want to purchase your AssetStore product.
This tool is definitely a brand new design for develop,
I always spend hours to find out what makes the animation glitch,
especially when I working with playable graph.
