### ISSUE TITLE
Don't know why is not working :(

### ISSUE THREAD

**Issue by davidlehub** [handzlikchris/Unity.MissingUnityEvents#5]
When i change the position, not thing happen ! Here is the my code:
`using System;
using UnityEngine;

namespace AssetsTest
{
	class Class1 : MonoBehaviour
	{
		[SerializeField]
		private Transform follow;

		//private void Awake()
		private void Start()
		{
			follow.SetPositionExecuting += Follow_SetPositionExecuting;
		}

		private void Follow_SetPositionExecuting(object sender, Vector3 e)
		{
			Debug.Log("020210207185411");
		}
	}
}
`
Thanks in advance for any help

**Comment by handzlikchris** [comment]
Hi David,

Looks like you got the setup right (otherwise you'd be getting compilation error that SetPositionExecuting) does not exist.

Rifht now this is standard c# event, there's preatty much nothing that could go wrong in there.
Probably best to take a step back and confirm that the position is actually being set? and it's also actually being set by .position setter and not some other way.

Just to  test if the tool works you can adjust .position yourself from some other script and it needs to fire. Perhaps also attaching debugger and seeing the code line by line could help. Maybe there's some issue and your code actually did not compile hence is not executing?

Thanks,
Chris

**Comment by davidlehub** [comment]
Hi Chris, thank you for your help! Follow your guide, it work now ☺

You save me a lots of.. "why, why ,why..." it doesn't work since there was
no error warning in code. Have tried things left and right (watching and
re-watching the GIF's  documentation, even reinstalling the tool, etc.).
Luckily, before been totally discourage, I decided to ask help from some
pro 😊

The reason it didn't work: I was just changing the position by using the
scene view gizmo, or by manually changing the position value in the
inspector, then expecting some thing would trigger.

Again, thanks, for the help and making/sharing that great tool! Have a nice
day
David

**Comment by handzlikchris** [comment]
Cool, glad I could help.
