### ISSUE TITLE
how to insert event in functions

### ISSUE THREAD

**Issue by zx1299** [handzlikchris/Unity.MissingUnityEvents#7]
if i want insert event when function call start or end, how to do?
such as when a gameobject.SetActive is called

thx

**Comment by handzlikchris** [comment]
I'm afraid the tool won't support that. Right now it's only working with properties.

I'd probably not be too difficult to add, the actual code that does the weaving is here
`https://github.com/handzlikchris/AddingEventsToCompiled3rdPartyLibrary` - potentally could get you going to get methods hooked up as well.

Also there's another tool that does IL rewriting on your code (rather than Unity dlls) which would also need a change but it should be simpler than trying to hook up into Unity extern methods.

`https://github.com/handzlikchris/Unity.TransformSetterInterceptor`
